name: Build and Sign

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Build Electron app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-file release/sbom.json
      
      - name: Generate checksums
        shell: bash
        run: |
          cd release
          if command -v sha256sum >/dev/null 2>&1; then
            for file in *.exe *.dmg *.AppImage *.deb *.zip 2>/dev/null; do
              [ -f "$file" ] && sha256sum "$file" >> SHA256SUMS.txt
            done
          else
            for file in *.exe *.dmg *.AppImage *.deb *.zip 2>/dev/null; do
              [ -f "$file" ] && shasum -a 256 "$file" >> SHA256SUMS.txt
            done
          fi
      
      - name: Write signing key
        run: echo "${{ secrets.SIGNING_SECRET_KEY }}" > signing.key
        
      - name: Sign releases
        run: node scripts/sign-release.js
        env:
          SECRET_KEY_PATH: ./signing.key
      
      - name: Clean up signing key
        if: always()
        run: rm -f signing.key
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            release/*.exe
            release/*.dmg
            release/*.AppImage
            release/*.deb
            release/*.zip
            release/*.sig
            release/manifest.json
            release/manifest.json.sig
            release/sbom.json
            release/SHA256SUMS.txt
          retention-days: 30
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
